"""
Test suite for ChromaDB Manager
"""
from chroma_manager import ChromaDBManager


def run_tests():
    """Run all tests for the ChromaDB Manager"""
    print("=" * 80)
    print("FACULTY PULSE - CHROMADB MANAGER TEST SUITE")
    print("=" * 80)

    # Initialize the manager
    print("\n[TEST 1] Initializing ChromaDB Manager...")
    manager = ChromaDBManager()
    print("✓ ChromaDB Manager initialized successfully")

    # Example 1: Add submission from JSON file
    print("\n" + "-" * 80)
    print("[TEST 2] Adding submission from JSON file (data_example.json)...")
    print("Expected: Submission with ID 'sub_001' should be added")
    manager.add_submission_from_json("data_example.json")
    print("✓ Test 2 passed")

    # Example 2: Add a single submission with explicit ID
    print("\n" + "-" * 80)
    print("[TEST 3] Adding a single submission with explicit ID 'sub_006'...")
    print("Expected: Submission should be added with ID 'sub_006'")
    manager.add_single_submission(
        document="Dr. Williams published a groundbreaking study on climate change adaptation strategies in coastal communities.",
        faculty_name="Dr. Jennifer Williams",
        date_published="2026-01-12T11:00:00Z",
        content_type="Publication",
        department="Environmental Science",
        submission_id="sub_006"
    )
    print("✓ Test 3 passed")

    # Example 3: Add a single submission with autogenerated ID
    print("\n" + "-" * 80)
    print("[TEST 4] Adding a single submission with autogenerated ID...")
    print("Expected: Submission should be added with a UUID")
    manager.add_single_submission(
        document="Dr. Chen delivered an inspiring keynote on artificial intelligence ethics at the International Tech Conference.",
        faculty_name="Dr. Michael Chen",
        date_published="2026-01-11T09:00:00Z",
        content_type="Talk",
        department="Computer Science"
    )
    print("✓ Test 4 passed")

    # Check collection count
    print("\n" + "-" * 80)
    print("[TEST 5] Checking collection count...")
    count = manager.get_collection_count()
    print(f"Total submissions in collection: {count}")
    print(f"✓ Test 5 passed - Found {count} submissions")

    # Query example - all submissions
    print("\n" + "-" * 80)
    print("[TEST 6] Querying all submissions about 'award'...")
    print("Expected: Should return submissions ranked by relevance")
    results = manager.query_submissions("award", n_results=3)
    print(f"Found {len(results['ids'][0])} results:")
    for i, (doc_id, doc, metadata, distance) in enumerate(zip(
        results['ids'][0],
        results['documents'][0],
        results['metadatas'][0],
        results['distances'][0]
    ), 1):
        print(f"  {i}. ID: {doc_id}")
        print(f"     Faculty: {metadata['faculty_name']}")
        print(f"     Type: {metadata['content_type']}")
        print(f"     Similarity: {1 - distance:.4f}")
        print(f"     Document: {doc[:100]}...")
    print("✓ Test 6 passed")

    # Query with filters
    print("\n" + "-" * 80)
    print("[TEST 7] Querying Publications only (filtered by content_type)...")
    print("Expected: Should return only publications")
    results = manager.query_submissions(
        query_text="research",
        n_results=5,
        content_type="Publication"
    )
    print(f"Found {len(results['ids'][0])} publication(s):")
    for i, (doc_id, metadata) in enumerate(zip(results['ids'][0], results['metadatas'][0]), 1):
        print(f"  {i}. {metadata['faculty_name']} - {metadata['content_type']} (ID: {doc_id})")
    print("✓ Test 7 passed")

    # Query by department
    print("\n" + "-" * 80)
    print("[TEST 8] Querying Computer Science department (filtered by department)...")
    print("Expected: Should return only Computer Science submissions")
    results = manager.query_submissions(
        query_text="technology",
        n_results=5,
        department="Computer Science"
    )
    print(f"Found {len(results['ids'][0])} submission(s) from Computer Science:")
    for i, (doc_id, metadata) in enumerate(zip(results['ids'][0], results['metadatas'][0]), 1):
        print(f"  {i}. {metadata['faculty_name']} - {metadata['content_type']} (ID: {doc_id})")
    print("✓ Test 8 passed")

    # Display all submissions
    print("\n" + "-" * 80)
    print("[TEST 9] Displaying all submissions in database...")
    print("Expected: Should show all submissions with full details")
    manager.display_all_submissions()
    print("✓ Test 9 passed")

    print("\n" + "=" * 80)
    print("ALL TESTS PASSED ✓")
    print("=" * 80)


if __name__ == "__main__":
    run_tests()
